# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :install_deps do
  spm(command: "resolve")
end

desc "Test Swift code and templates"
lane :test do
  test_src
  test_templates
end

desc "Test code compilation into templates and templates code generation"
lane :test_templates do
  sh "cd .. && ./Scripts/generate-annotation-template"
  sh "cd .. && swift run sourcery --sources Sources --output Generated --templates Templates"

end

desc "Run Swift tests on sources"
lane :test_src do
  sh "cd .. && swift test --enable-test-discovery"
end
