#! /bin/sh -e

SCRIPTPATH=$(dirname "$0")
TEMPLATES=${TEMPLATES:-"$SCRIPTPATH/../Templates"}

if [ -z "SOURCERY_BINPATH" ]; then
  SOURCERY_BINPATH="$SOURCERY_BINPATH"
elif [ -f "$PODS_ROOT/Sourcery/bin/sourcery" ]; then
  SOURCERY_BINPATH="$PODS_ROOT/Sourcery/bin/sourcery"
else
  SOURCERY_BINPATH="sourcery"
fi

if [ ! -f "$SCRIPTPATH/../Sources" ]; then
    "$SCRIPTPATH/generate-annotation-template"
fi

set -x

"$SOURCERY_BINPATH" --templates "$TEMPLATES" "$@"
