name: Run tests and build sample

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: check swift
      run: xcode-select -p

    - name: Run tests
      run: fastlane test