name: Run tests and build sample

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: macos-latest
    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Fix Xcode path for Sourcery
      run: ln -s /Applications/$(xcode-select -p | cut -d "/" -f 3) /Applications/Xcode.app

    - name: Run tests
      run: fastlane test